Create DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE USUARIO(
	NOMBRE CHARACTER(20),
    APELLIDOS CHARACTER (20),
    EDAD INTEGER(2),
    DNI CHARACTER(20),
    ESTADO CHARACTER(20));

    

CREATE TABLE LIBROS(
	CODIGO INTEGER(2) primary KEY,
	NOMBRE CHARACTER(20),
    CATEGORIA CHARACTER(20),
    PRESTAMO CHARACTER (20));
    
ALTER TABLE LIBROS ADD(EDITORIAL CHARACTER(20));
    

 
CREATE TABLE periodico(
	CODIGO INTEGER(2) primary KEY,
	NOMBRE CHARACTER(20),
    EDITORIAL CHARACTER(20),
    TIPODENOTICIAS CHARACTER(20),
    PRESTAMO CHARACTER (20));   
   

CREATE TABLE REVISTA(
	CODIGO INTEGER(2) primary KEY,
	NOMBRE CHARACTER(20),
    TIPOREVISTA CHARACTER(20),
    AUTOR CHARACTER(20),
    PRESTAMO CHARACTER (20));   


CREATE TABLE GESTOR (
	NIF CHARACTER(20)PRIMARY KEY,
    NOMBRE CHARACTER(20),
    APELLIDO CHARACTER(20),
    EDAD INTEGER(2));



    SELECT * FROM GESTOR;
INSERT INTO GESTOR VALUES('54373314A','NICOLAS','FERNANDEZ',22);
INSERT INTO PERIODICO VALUES(2,'EL MUNDO','planetamundo','en uso','deporte');

select * from periodico;

delete from gestor
where edad=18;