Create DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE USUARIO(
	NOMBRE CHARACTER(20),
    APELLIDOS CHARACTER (20),
    EDAD INTEGER(2),
    DNI CHARACTER(20),
    ESTADO CHARACTER(20));

    

CREATE TABLE LIBROS(
	CODIGO INTEGER(2) primary KEY,
	NOMBRE CHARACTER(20),
    CATEGORIA CHARACTER(20),
    PRESTAMO CHARACTER (20));
    
ALTER TABLE LIBROS ADD(EDITORIAL CHARACTER(20));
    

 
CREATE TABLE periodico(
	CODIGO INTEGER(2) primary KEY,
	NOMBRE CHARACTER(20),
    EDITORIAL CHARACTER(20),
    TIPODENOTICIAS CHARACTER(20),
    PRESTAMO CHARACTER (20));   
   

CREATE TABLE REVISTA(
	CODIGO INTEGER(2) primary KEY,
	NOMBRE CHARACTER(20),
    TIPOREVISTA CHARACTER(20),
    AUTOR CHARACTER(20),
    PRESTAMO CHARACTER (20));   


    SELECT * FROM REVISTA;
INSERT INTO REVISTA VALUES(6,'el pais','DEPORTE','RODRIGUEZ','no en uso');
INSERT INTO PERIODICO VALUES(2,'EL MUNDO','planetamundo','en uso','deporte');

select * from PERIODICO;

delete from REVISTA
where codigo=5;