Create DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE USUARIO(
	NOMBRE CHARACTER(20),
    APELLIDOS CHARACTER (20),
    EDAD INTEGER(2),
    DNI CHARACTER(20),
    ESTADO CHARACTER(20));

    

CREATE TABLE LIBROS(
	CODIGO INTEGER(2) primary KEY,
	NOMBRE CHARACTER(20),
    CATEGORIA CHARACTER(20),
    PRESTAMO CHARACTER (20));
    
ALTER TABLE LIBROS ADD(EDITORIAL CHARACTER(20));
    

 
CREATE TABLE periodico(
	CODIGO INTEGER(2) primary KEY,
	NOMBRE CHARACTER(20),
    EDITORIAL CHARACTER(20),
    TIPODENOTICIAS CHARACTER(20),
    PRESTAMO CHARACTER (20));   
   

CREATE TABLE REVISTA(
	CODIGO INTEGER(2) primary KEY,
	NOMBRE CHARACTER(20),
    TIPOREVISTA CHARACTER(20),
    AUTOR CHARACTER(20),
    PRESTAMO CHARACTER (20));   


    SELECT * FROM revista;
INSERT INTO LIBROS VALUES(1,'PRUEBA','FANTASIA','NO EN USO','planetamundo');

select * from periodico;

delete from periodico
where nombre='la morte';